language: node_js
node_js:
  - 7
sudo: required

services:
-docker

before_install:
-{TRAVIS_BUILD_DIR}/docker-nodeprof/docker-build.sh
- npm install
- npm run build
- jest -t basic-assignment-tainted

